kaena-734: fix updating of reader morsels
- Added full_dependency option to separate it from enable_cleanup

- Also cleanup wavechecker errors in partial dependency flow of the following type, by properly forcing transitive dependencies through readers of SB atoms:

ERROR: Potential RAW or WAR hazard in SB between R:max_pooling2d_1/MaxPool/Pool_n0_m0_h12_w0 and W:activation_1/Relu/Activation_n0_m0_h52_w0
        SB Write range : [96512, 96959]
        SB Read range : [94720, 96733]

- Added fanout check to grep_waveop_type.py

- Cleanup test_list.py help manage ME options

Change-Id: I0bdd934e6e627d284350739c66a65182fc5efade
Signed-off-by: Jeffrey Huynh <jthuynh@amazon.com>